[appendix]
[[annex-c]]
:appendix-caption: Annex

== JSON Resources Schema and Documentation (Was Clause 7.6 in 1.1)
This section provides a detailed, logical-level specification for each of the resource types.

=== Basic Value Types
A value schema ensures that the JSON properties follow a fixed pattern and support the following data types:

.	String: utf8 String.
.	Float: A Float64 number with an optional fractional component, such as "1.02" or "1.0".
.	Integer: An Int32 number without a fractional component, such as "234".
.	UUID: A canonical hexadecimal UUID, such as "550e8400-e29b-41d4-a716-446655440000".
.	Date: An ISO 8601 timestamp YYYY-MM-DDThh:mm:ss.sTZD, with a fixed "Z" time zone, such as "2009-01-01T12:00:00.000Z".
.	URL: Any resolvable, relative or absolute, URL, such as "../Node/51/sharedResource".
.	Pointer: Any resolvable reference to an object in a JSON document, consisting of a relative or absolute URL and a document path, such as [../Node/51/sharedResource]/materialDefinitions/Mat01 .
.	NodeID: A treekey string such as “3-0-34-234-2” that is zero-based (first child is "0", root node is "root").

=== Pointers
The I3S Standard specifies the following Pointer syntax whenever a specific property in the current or another document is to be referenced. The Pointer consists of two elements:

.	Mandatory in-document reference: Relative to the currently evaluated property, or document absolute, reference to a property. References are always slash-separated paths through a document tree and can contain wildcards (\*) to indicate that a set or list of properties is to be matched instead of a single property.

**	Absolute references start with a slash (/). Absolute references may only contain upstream path elements; i.e. they may only point to properties of objects enclosing the property that is being evaluated and indicated by a name.

***	Example: ```/materialDefinitions/*/type```

**	Relative references start with a property key (e.g. type). Relative properties may only contain downstream path elements and are evaluated from the value being tested. They may not contain wildcards, as appropriate context is already given through the current element being evaluated. In the case of a property that has containerType set to Array or Object, the reference point for a relative path is the individual value element in the container.

***	Example: ```params/ambient/0```

.	Optional URL: The pointer may be prefixed with a URL to a different document. This URL may be relative to the document that is being evaluated or absolute. To identify the URL element of a pointer, it is given in square brackets. Examples:

**	relative URL + absolute reference: From FeatureData to 3dSceneLayer.name: ```[../../]/name```
**	absolute URL + absolute reference: ```http://my_server/my_service/rest/services/Buildings_Portland/SceneServer/layers/0/nodes/68```
