[appendix]
[[annex-a]]
:!numbered:
:appendix-caption: Annex

== I3S Scene Layer Profile - Mesh-pyramids (MP)

This Annex is provided for further guidance and information on Mesh-pyramids. 

NOTE: This Annex was originally provided in OGC I3S Version 1.1. This annex is provided in 1.2 with the caveat that only 1.1 Classes and resources are used in the examples and guidance below. While 1.2 has all of the required 1.1 compatible classes, the enhancements and extensions for node indexing, geometry compression, and materials are not considered in the discussion below.

What this profile is used for: This profile is implemented by the 3D Object and Integrated Mesh layer types.

=== Access Pattern

This section describes how a client is expected to load and handle resources from an Indexed 3D Scene Layer using the
Mesh-pyramids profile. The general pattern consists of these phases:

.	Handshake & capabilities negotiation: The client ensures that the service has the expected resources and that a client and a server have a common set of capabilities. Within this phase, the client utilizes the following resources:
..	Retrieve SceneServiceInfo: General service information
..	Retrieve 3dSceneLayer: Information on available layers, including symbology and encoding
.	Index exploration: The client retrieves Node Index Documents and decides – based on lodSelection properties – whether it wants to download and render their attached resources. Within this phase, the client utilizes the following resource:
..	NodeIndexDocument: Summary of the content of a single node of the index, references children, parent and neighbor nodes, indicating what can be found there
.	Rendering: When a client has decided that it wants to render the content of a node, it retrieves the attached resources:
..	SharedData: Material definitions, shared geometries for instancing
..	GeometryData: Geometry attributes such as positions and indices
..	TextureData: Images used as texture maps
..	AttributeData: Attribute data of features used for attribute-based symbolization (as indicated by the DrawingInfo object in the 3dSceneLayer resource)
.	Identify: Additional resources belonging to a node are accessed only if needed, e.g. for an Identify operation.
..	AttributeData: If the AttributeData resources of the node have not already been fetched (in step 3 above) client application can request the desired attribute data.

A familiar access pattern based on a single tree data structure is proposed for view frustum culling, level-of-detail selection,
and rendering. The following pseudo code illustrates the recommended pattern when navigating an index tree using Mesh Pyramids.
Node traversal starts at the root node and recursively calls TraverseNodeTree(node):

```
TraverseNodeTree(node)
{
    if (node’s mbs is not visible) // see 1)
        // do nothing
    else if (node has no children or ScreenSize(mbs) < maxScreenThreshold) //see 2)
        // render the node // see 3)
    else
        for each child in children(node) // see 4)
            TraverseNodeTree(child);
}
```

=== Additional notes:

.	view frustum culling:
..	visibility test can include the ‘entirely inside the viewing frustum’ result which can be used to optimize away all further frustum culling tests on the children of the node
..	this step can also optionally incorporate a cutoff distance threshold test if desired.
.	level-of-detail selection:
..	test used to decide how deep to recurse is based on mbs‘ projected size (diameter) on the screen vs the per node provided ‘maxScreenThreshold’.
.	Rendering:
..	“render the node” potentially includes some, or all, of the following steps:
...	Requesting the corresponding geometry and texture data if not already requested
...	(asynchronously) accessing the corresponding geometry and texture data and loading it into GPU memory if not already loaded
...	Binding, if loaded, the geometry VBO
...	Binding, if loaded, the texture
...	Making a draw() call if, at least, the geometry is loaded
.	optimized user experience:
..	children should be sorted by the ascending distance from the observer…

=== Schema
The mesh pyramids profile makes use of all 7 main resource types and allows for a restricted set of properties. Note that the FeatureData resource is optional for this profile. Hence the 3dSceneLayer resource must contain a DefaultGeometrySchema.

=== SceneServiceInfo
No specific profile.

=== 3dSceneLayer
Note that in this profile, the DefaultGeometrySchema is mandatory.

link:../docs/3dSceneLayer.cmn.adoc[3dSceneLayer]

=== 3dNodeIndexDocument
There is always exactly 1 geometry and texture resource per node.

link:../docs/3dNodeIndexDocument.cmn.adoc[3dNodeIndexDocument]

=== AttributeData
Attribute data for all features in a node is stored and made available as discrete, per field resource called attribute. The number of attribute resources corresponds to the number of feature data fields that are chosen to be included along with the 3d Scene Layer cache.

=== FeatureData
The FeatureData is optional with this profile.

FeatureData

=== SharedResources
SharedResources

```{
  "id": 0,
  "version": "3d3c7b51-6336-4893-b484-ad118775bcce",
  "name": "Export2",
  "href": "./layers/0",
  "layerType": "IntegratedMesh",
  "ZFactor": 1.0,
  "spatialReference": {
    "wkid": 4326,
    "latestWkid": 4326
  },
  "alias": "Export2",
  "description": "Vricon 3D Surface Model",
  "copyrightText": "Limited in accordance with the accompanying Vricon EULA",
  "capabilities": [
    "View",
    "Query"
  ],
  "store": {
    "id": "e9ecfade-0d85-4dd7-abb5-a3b0a07b9fd7",
    "profile": "meshpyramids",
    "resourcePattern": [
      "3dNodeIndexDocument",
      "SharedResource",
      "Geometry",
      "Attributes"
    ],
    "rootNode": "./nodes/root",
    "version": "1.4",
    "extent": [
      -106.5054122583675,
      38.994677805489189,
      -103.99630101552692,
      39.996971340614706
    ],
    "indexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
    "vertexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
    "nidEncoding": "application/vnd.esri.i3s.json+gzip; version=1.4",
    "featureEncoding": "application/vnd.esri.i3s.json+gzip; version=1.4",
    "geometryEncoding": "application/octet-stream; version=1.4",
    "attributeEncoding": "application/octet-stream; version=1.4",
    "textureEncoding": [
      "image/jpeg",
      "image/vnd-ms.dds"
    ],
    "lodType": "MeshPyramid",
    "lodModel": "node-switching",
    "defaultGeometrySchema": {
      "geometryType": "triangles",
      "header": [
        {
          "property": "vertexCount",
          "type": "UInt32"
        },
        {
          "property": "featureCount",
          "type": "UInt32"
        }
      ],
      "topology": "PerAttributeArray",
      "ordering": [
        "position",
        "normal",
        "uv0",
        "color"
      ],
      "vertexAttributes": {
        "position": {
          "valueType": "Float32",
          "valuesPerElement": 3
        },
        "normal": {
          "valueType": "Float32",
          "valuesPerElement": 3
        },
        "uv0": {
          "valueType": "Float32",
          "valuesPerElement": 2
        },
        "color": {
          "valueType": "UInt8",
          "valuesPerElement": 4
        }
      },
      "featureAttributeOrder": [
        "id",
        "faceRange"
      ],
      "featureAttributes": {
        "id": {
          "valueType": "UInt64",
          "valuesPerElement": 1
        },
        "faceRange": {
          "valueType": "UInt32",
          "valuesPerElement": 2
        }
      }
    }
  }
}
```
