== Scope

Scene Layers provide a structured way for clients to store and visualize large volumes of 3D data. I3S organizes information into node hierarchies that contain features with geometry, textures and attributes.

A Scene Layer is characterized by a combination of `layer type` and `profile`. The layer type describes the kind of geospatial data stored within it. The profile includes additional details on the specific I3S rules for implementation.  `layer type` and `profile` fully describe the behavior of the layer. For example, the profile type `MeshPyramids` is a specific implementation instance that is used in integrated mesh scene layers, 3D object scene layers, and sublayers of building scene layers.

The I3S format is declarative and extendable and can be used to represent different types of 3D data. The following layer types have been specified and the validated via implementation and production deployments:

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/3Dobject_ReadMe.adoc[*3D Objects*] such as Building Exteriors from geospatial data (GIS) and 3D models in various formats.

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/IntegratedMesh_ReadMe.adoc[*Integrated Meshes*] such as a mesh surface with high resolution imagery textures representing the skin of the Earth, typically created from satellite, aerial or drone imagery.

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/Point_ReadMe.adoc[*Point Features*] such as geolocated hospitals or schools, trees, street furniture, and signs.

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/pcsl_ReadMe.adoc[*Point Clouds]* such as large point data collections from LiDAR.

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/BSL_ReadMe.adoc[*Building Scene Layer*] - comprehensive building model including building components.

The specification of the indexed 3D scene layer (I3S) and the specification for accessing I3S resources as scene service REST endpoints are described in this document as open formats. The REST endpoint implementations are described for each layer type.

I3S is designed to support large datasets of 3D content ranging from local to global extent containing detailed features. Clients can visualize scene layers by taking advantage of the multi-LoD (level of detail) representation and symbology to create the right user experience for visualizing the 3D content. The I3S format continues to evolve and new functionality continues to be added.

I3S is organized as <<i3snodes,nodes>>, which are structured into node pages. The node page includes the bounding volume, child reference, count and the level of detail selection. Nodes contain all the information to describe features including geometry, attributes and textures. Scene Layers can be created in cartesian 3D or in global 3D world coordinate reference systems. I3S Scene Layers can be delivered to web, mobile and desktop clients. Most users will interact with Scene Layers using applications with cloud or server-based information. In these cases, the scene layer content is on the server and is provided to clients through a RESTful interface. These web addressable resources provide access to the scene layer, nodes, and associated resources. Alternatively, a scene layer can be delivered as a Scene Layer Package. This is a single file that includes the complete node tree and all necessary resources in an archive.

The Indexed 3d Scene Layer (I3S) and Scene Layer Package (*.slpk) are open formats and not dependent on any vendor specific solution, technology, or products.[3] The specification for accessing I3S resources as Scene Service REST endpoints is also described in this standard as open formats.
