== Introduction to I3S and SLPK

This section provides background information on the design principals and background for I3S

=== I3S Design Principals

The Indexed 3d Scene layer (I3S) format and the corresponding Scene Layer Package format (*.slpk) are specified to fulfill this set of design principles: 

- *User Experience first*: Provide a positive user experience, including high interactivity and fast display;
- *Scalability*: Support very large scene layers, including scenes with a global extent and many detailed features;
- *Reusability*: Use as a service delivery format, storage format, and exchange format;
- *Level of Detail*: Have support for multiple levels of detail;
- *Distribution*: Allow efficient distribution of very large data sets;
- *User-controllable symbology*: Support efficient rendering of client-side symbology/styling;
- *Extensibility*: Support new layer, geometry types and new platforms;
- *Web Friendliness*: Provide easy to handle data using JSON and current web standards;
- *Compatibility*: Provide a single structure that is compatible across web, mobile, and desktop clients. Support is also included for cloud and servers;
- *Declarative*: Communicate clearly to minimize the amount of required domain knowledge to support the format; Follow REST/JSON API best practices: Provide navigable links to all resources.

=== I3S Overview

Scene Layers provide a structured way for clients to store and visualize large volumes of 3D data. I3S organizes information into node hierarchies that contain features with geometry, textures and attributes.

An I3S Layer is characterized by a combination of `layer type` and `layer profile`. The `layer type` describes the kind of geospatial data stored within it. The `layer profile` includes additional details on the specific I3S implementation for the layer that is exposed to clients. Each layer has a canonical profile, but in certain cases multiple layers that represent semantically different types of information can make use of the same underlying profile. In other cases the same layer type can support multiple profiles optimized for different use cases. 

The current scene layer profile types are:

- https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/3Dobject_ReadMe.adoc[3D Object] such as 3D models in various formats.
-	https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/IntegratedMesh_ReadMe.adoc[Integrated Mesh] such as a mesh surface with high resolution imagery textures representing the skin of the Earth, typically created from satellite, aerial or drone imagery. A profile for integrated meshes is described in <<annex-a,I3S Scene Layer Profile - Mesh-pyramids (MP)>>
-	https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/Point_ReadMe.adoc[Point] such as geolocated hospitals or schools, trees, street furniture, and signs.
-	https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/pcsl_ReadMe.adoc[Point Cloud] such as LiDAR data. 
- https://github.com/opengeospatial/ogc-i3s-community-standard/blob/main/docs/BSL_ReadMe.adoc[Building]: A building including its components, such as windows, doors, electrical, plumbing, and so on.

An I3S data set is organized as <<i3snodes,nodes>> and layers. Nodes are structured into <<nodepages,node pages>>. The node page includes the bounding volume, child reference, count and the <<lodselection,level of detail selection>>. Nodes contain all the information to describe features including <<i3sgeometry,geometry>>, <<i3sattributes,attributes>>, and <<i3stectures,textures>>. Scene Layers can be created in cartesian 3D or in global 3D world <<i3scrs,coordinate reference systems>>. I3S Scene Layers can be delivered to web, mobile and desktop clients. Most users will interact with Scene Layers using applications with cloud or server-based information. In these cases, the scene layer content is on the server and is provided to clients through a RESTful interface. These web addressable resources provide access to the scene layer, nodes, and associated resources. Alternatively, a scene layer can be delivered as a Scene Layer Package. This is a single file that includes the complete node tree and all necessary resources in an archive.

The following table shows the layer types and profiles. For each row the table indicates if the layer type represents features (geographic entities) with identity (as opposed to a geospatial field described by a mesh or cloud of geometry elements) and if the specific profile for the layer supports storage of attributes (either feature attributes or attributes of individual geometry elements, depending on the type of the layer).

[#table_layertypes,reftext='{table-caption} {counter:table-num}']
.*3D Layer Types Supported in I3S*
[width="90%",options="header"]
|===
|Layer Type (example) |	Profile |	Features with Identity |Attributes
|https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/3Dobject_ReadMe.adoc[3D Object] |	mesh-pyramids	|Yes	|Yes
|https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/IntegratedMesh_ReadMe.adoc[Integrated Mesh] |mesh-pyramids	 |No	|Triangle Attributes (planned)
|https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/Point_ReadMe.adoc[Point]| points	 |Yes	|Yes
|https://github.com/opengeospatial/ogc-i3s-community-standard/tree/main/docs/pcsl_ReadMe.adoc[Point Cloud]	|pointclouds  |	No|Vertex Attributes
|https://github.com/opengeospatial/ogc-i3s-community-standard/blob/main/docs/BSL_ReadMe.adoc[Building Scene Layer]	|Building Scene Layer |	Yes| Yes
|===

