== Introduction to I3S and SLPK

This section provides background information on the design principals and background for I3S

=== I3S Design Principals

The Indexed 3d Scene layer (I3S) format and the corresponding Scene Layer Package format (*.slpk) are specified to fulfill this set of design principles: 

- *User Experience first*: Provide a positive user experience, including high interactivity and fast display;
- *Scalability*: Support very large scene layers, including scenes with a global extent and many detailed features;
- *Reusability*: Use as a service delivery format, storage format, and exchange format;
- *Level of Detail*: Have support for multiple levels of detail;
- *Distribution*: Allow efficient distribution of very large data sets;
- *User-controllable symbology*: Support efficient rendering of client-side symbology/styling;
- *Extensibility*: Support new layer, geometry types and new platforms;
- *Web Friendliness*: Provide easy to handle data using JSON and current web standards;
- *Compatibility*: Provide a single structure that is compatible across web, mobile, and desktop clients. Support is also included for cloud and servers;
- *Declarative*: Communicate clearly to minimize the amount of required domain knowledge to support the format; Follow REST/JSON API best practices: Provide navigable links to all resources.

=== I3S Overview

A single I3S data set, referred to as a Scene Layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. Scene Layers provide clients access to data and allow them to visualize it according to their needs.   Data here refers to vertex geometry, texture as well as any associated attributes. 

An I3S Layer is characterized by a combination of layer type and profile. The _layer type_ describes the kind of geospatial data stored within it. The _layer profile_ includes additional details on the specific I3S implementation. 

The requirements specified below apply to the following layer types defined in this standard:

- 3D Objects such as Building Exteriors from geospatial data and 3D models.
-	Integrated Meshs such as a mesh surface with high resolution imagery textures representing the skin of the Earth, typically created from satellite, aerial or drone imagery. 
-	Points such as geolocated hospitals or schools, trees, street furniture, and signs.
-	Point Clouds such as LiDAR data. 

Layers are described using two properties: type and profile. The type of a layer describes the type of geospatial data stored within it drawing from terms including 3D Objects, Points, Lines, Polygons, and Point Clouds. The profile for a layer includes additional detail on the specific I3S implementation for the layer that is exposed to clients. Each layer has a canonical profile, but in certain cases multiple layers that represent semantically different types of information can make use of the same underlying profile. In other cases the same layer type can support multiple profiles optimized for different use cases. 

The following table shows the layer types and profiles. For each row the table indicates if the layer type represents features (geographic entities) with identity (as opposed to a geospatial field described by a mesh or cloud of geometry elements) and if the specific profile for the layer supports storage of attributes (either feature attributes or attributes of individual geometry elements, depending on the type of the layer).

[#table_layertypes,reftext='{table-caption} {counter:table-num}']
.*3D Layer Types Supported in I3S*
[width="90%",options="header"]
|===
|Layer Type (example) |	Profile |	Features with Identity |Attributes
|link:3Dobject_ReadMe[3D Objects]|	mesh-pyramids	|Yes	|Yes
|Integrated Mesh|mesh-pyramids	 |No	|Triangle Attributes (planned)
|Point| points	 |Yes	|Yes
|Point Cloud	|pointclouds  |	No|Vertex Attributes
|===

