[[scope]]
== Scope

A single I3S data set, referred to as a Scene Layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. Scene Layers provide clients access to data and allow them to visualize it according to their needs. The definition of "data" in this case includes the geometry, attributes, and vertex geometry.

A Scene Layer is characterized by a combination of layer type and profile.  The _layer type_ describes the kind of geospatial data stored within it. The _layer profile_ includes additional details on the specific I3S implementation.

The I3S format is declarative and extendable and can be used to represent different types of 3D data. The following layer types have been specified and the standard validated via implementation and production deployments:

* <<3dobjects,3D Objects>> such as Building Exteriors from geospatial data and 3D models.
* Integrated Meshes such as a mesh surface with high resolution imagery textures representing the skin of the Earth, typically created from satellite, aerial or drone imagery.
* Point Features such as geolocated hospitals or schools, trees, street furniture, and signs.
* Point Clouds such as large point data from LiDAR. 

The Indexed 3d Scene Layer (I3S) and Scene Layer Package (*.slpk) are open formats and not dependent on any vendor specific solution, technology, or products . The specification for accessing I3S resources as Scene Service REST (Annex E of this document) endpoints is also described as open formats.
