:Title: OGC Indexed 3d Scene Layer (I3S) and Scene Layer Package Format Community Standard Version 1.2
:titletext: {Title}
:doctype: book
:encoding: utf-8
:lang: en
:toc:
:toc-placement!:
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter: pygments

<<<
[cols = ">",frame = "none",grid = "none"]
|===
|{set:cellbgcolor:#FFFFFF}
|[big]*Open Geospatial Consortium*
|Submission Date: <2019-mm-dd>
|Approval Date:   <2019-mm-dd>
|Publication Date:   <2019-mm-dd>
|External identifier of this OGC(R) document:  http://www.opengis.net/doc/CS/i3s/1.2
|Internal reference number of this OGC(R) document:    17-014r8
|Version: 1.2
|Category: OGC(R) Implementation
|Editors:   Carl Reed, Tamrat Belayneh 
|===

[cols = "^", frame = "none"]
|===
|[big]*{titletext}*
|===

[cols = "^", frame = "none", grid = "none"]
|===
|*Copyright notice*
|Copyright (C) 2021 Open Geospatial Consortium
|To obtain additional rights of use, visit http://www.opengeospatial.org/legal/
|===

[cols = "^", frame = "none"]
|===
|*Warning*
|===

This document is not an OGC Standard. This document is distributed for review and comment. This document is subject to change without notice and may not be referred to as an OGC Standard.

Recipients of this document are invited to submit, with their comments, notification of any relevant patent rights of which they are aware and to provide supporting documentation.

[width = "50%", grid = "none"]
|===
|Document type:   	OGC® Community Standard
|Document subtype:   	if applicable
|Document stage:   	Draft
|Document language: 	English
|===

<<<
License Agreement

Esri (Environmental Systems Research Institute, Inc.)

The companies listed above have granted the Open Geospatial Consortium (OGC) a nonexclusive, royalty-free, paid up, worldwide license to copy and distribute this document and to modify this document and distribute copies of the modified version under a Creative Commons ShareAlike (CC BY-SA) license (see below).

License Agreement
The standard is licensed under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) . You can implement this standard in services, clients or processing tools without restrictions.
You are directed to the License for specific details..
This is a human-readable summary of (and not a substitute for) the license.
You are free to:
•	Share — copy and redistribute the material in any medium or format
•	Adapt — remix, transform, and build upon the material for any purpose, even commercially.
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:

•	Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use. 
•	ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
•	No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
Notices: 
•	You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
•	No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

<<<
toc::[]

<<<

////
Make sure to complete each included document
////
include::clause_0_front_material.adoc[]

include::clause_1_scope.adoc[]

include::clause_2_conformance.adoc[]

include::clause_3_references.adoc[]

include::clause_4_terms_and_definitions.adoc[]

include::clause_5_conventions.adoc[]

include::clause_6_informative_text.adoc[]

include::clause_7_normative_text.adoc[]

include::clause_8_formats_normative.adoc[]

include::clause_9_Supported_I3S_Layer_Structures.adoc[]

include::clause_10_Additional_Informative_Information.adoc[]

include::clause_10_Persistence.adoc[]

<<<
////
add or remove annexes after "A" as necessary
////
//// include::annex-a.adoc[]

<<<
////include::annex-b.adoc[]

<<<
////include::annex-c.adoc[]

<<<
////include::annex-d.adoc[]

<<<
////
Revision History should be the last annex before the Bibliography
Bibliography should be the last annex
////
include::annex-history.adoc[]

<<<
include::annex-bibliography.adoc[]
