==== 7.6.4.2	Class Store
The Class Store object describes the exact physical storage of a Layer. This enables the client to detect when multiple Layers are served from the same Store. Including multiple layers in a single store allows them to share resources. This enables efficient serving of many layers of the same content type, but with different attribute schemas or different symbology applied.

[#table_store,reftext='{table-caption} {counter:table-num}']
.*Attributes of the Class Store within the 3dSceneLayerInfo document*
[width="90%",options="header"]
|===
|Name	|Type	|Description
|id	|String	|A Store ID, unique across a SceneServer. Enables the client to discover which layers a part of a common store, if any. {meshes, polygons, points, lines, analytics, meshpyramids, pointclouds, symbols}
|*profile*	|String	|Indicates which profile this scene store fulfills. One of {meshes, points, analytics, meshpyramids, symbols, PointCloud}.
|resourcePattern	|String []	|Indicates the resources needed for rendering and the required order in which the client should load them. Possible values for each array string: +
`3dNodeIndexDocument`: JSON file describes a single index node within a store, with links to other nodes (children, sibling, and parent), links to feature data, geometry data and texture data resources, metadata such as metrics used for LoD selection, its spatial extent. [Read more](3DNodeIndexDocument.cmn.adoc) +
`SharedResource`: Shared resources are models or textures that can be shared among features within the same layer. +
`featureData`: The FeatureData JSON file(s) contain geographical features with a set of attributes, accessors to geometry attributes and other references to styling or materials. +
`Geometry`: Each geometry resource is an array of geometries. +
`Texture`: The texture resource for a node contains the images that are used as textures for the features stored in the node. +
`Attributes`: Attribute resource for node containing feature data attributes +
|rootNode	|string	|Relative URL to root node resource.
|*version*	|String	|Format version of this resource; used here again if this store hasn't been served by a 3D Scene Server.
|extent	|Number[4]	|The 2D spatial extent (xmin, ymin, xmax, ymax) of this store, in the horizontal indexCRS
|indexCRS	|String	|The horizontal CRS used for all minimum bounding spheres (mbs) in this store, identified by an OGC URL.
|vertexCRS	|String	|The horizontal CRS used for all "vertex positions" in this store, identified by an OGC URL.
|normalReferenceFrame |string	|Describes the coordinate reference frame used for storing normals. 
Possible values are: +
`east-north-up`: A value of east-north-up indicates that normals are stored in a node local reference frame defined by the easting, northing and up directions at the MBS center, and is only valid for geographic (WGS84) vertexCRS. +
`earth-centered`: A value of earth-centered indicates that normals are stored in a global earth-centered, earth-fixed (ECEF) reference frame where the x-axis points towards Prime meridian (lon = 0°) and Equator (lat = 0°), the y-axis points East towards lon = +90 and lat = 0 and the z-axis points North. It is only valid for geographic vertexCRS. +
`vertex-reference-frame`: A value of vertex-reference-frame indicates that normals are stored in the same reference frame as vertices and is only valid for projected vertexCRS +
|nidEncoding	|string	|MIME type for the encoding used for the Node Index Documents; format:
application/vnd.ogc.I3S.json+gzip; OGC ersion=1.1
|featureEncoding	|string	|MIME type for the encoding used for the Feature Data Resources; format:
application/vnd.ogc.I3S.json+gzip; OGC version=1.1
|geometryEncoding	|string	|MIME type for the encoding used for the Geometry Resources; format:
application/octet-stream; OGC version=1.1
|textureEncoding	|string[]	|MIME type(s) for the encoding used for the Texture Resources
|lodType	|String	|Optional field to indicate which LoD generation scheme is used in this store.
Possible values are: +
`MeshPyramid`: Used for integrated mesh and 3D Object Scene layers, which share similar data partitioning as well as traversal patterns and hence belong to the same profile. +
`AutoThinning`: Used by point scene layer. Indicates the I3S generator (‘cooker’) used automatic data thining techniques to build interior nodes (non-leaf nodes). +
`Clustering`: Used by point scene layer. Indicates the ‘cooker’ used data clustering algorithims to build interior nodes (non-leaf nodes). +
`Generalizing`: Also used by point scene layer. Indicates the ‘cooker’ used data generalization algorithims/techniques to build interior nodes (non-leaf nodes). 
|lodModel	|String	|optional field to indicate which LoD Switching mode clients have to use. One of {*node-switching*, none}.
|*defaultGeometrySchema*	|link:defaultGeometrySchema.adoc[defaultGeometrySchema] |A common, global ArrayBufferView definition that can be used if the schema of vertex attributes and face attributes is consistent in an entire cache; this is a requirement for meshpyramids caches.
|defaultTextureDefinition	|_texture_ | A common, global TextureDefinition  to be used for all textures in this store. The default texture definition uses a reduced profile of the full TextureDefinition, with the following attributes being mandatory: encoding, uvSet, wrap and channels.
|defaultMaterialDefinition	|_material_ |If a store uses only one material, it can be defined here entirely as a MaterialDefinition 
|===

Note: properties in bold are mandatory.
Table 5: Attributes of the Class Store within the 3dSceneLayerInfo document
For more details regarding point scene layer, see the store point scene layer.
For more details regarding point cloud scene layer, see the store point cloud scene layer.

=== Examples 

==== Example: Store example 

```json
 {
  "id": "e9ecfade-0d85-4dd7-abb5-a3b0a07b9fd7",
  "profile": "meshpyramids",
  "resourcePattern": [
    "3dNodeIndexDocument",
    "SharedResource",
    "Geometry",
    "Attributes"
  ],
  "rootNode": "./nodes/root",
  "version": "1.4",
  "extent": [
    -106.5054122583675,
    38.99467780548919,
    -103.99630101552692,
    39.99697134061471
  ],
  "indexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
  "vertexCRS": "http://www.opengis.net/def/crs/EPSG/0/4326",
  "nidEncoding": "application/vnd.esri.i3s.json+gzip; version=1.4",
  "featureEncoding": "application/vnd.esri.i3s.json+gzip; version=1.4",
  "geometryEncoding": "application/octet-stream; version=1.4",
  "attributeEncoding": "application/octet-stream; version=1.4",
  "textureEncoding": [
    "image/jpeg",
    "image/vnd-ms.dds"
  ],
  "lodType": "MeshPyramid",
  "lodModel": "node-switching",
  "defaultGeometrySchema": {
    "geometryType": "triangles",
    "header": [
      {
        "property": "vertexCount",
        "type": "UInt32"
      },
      {
        "property": "featureCount",
        "type": "UInt32"
      }
    ],
    "topology": "PerAttributeArray",
    "ordering": [
      "position",
      "normal",
      "uv0",
      "color"
    ],
    "vertexAttributes": {
      "position": {
        "valueType": "Float32",
        "valuesPerElement": 3
      },
      "normal": {
        "valueType": "Float32",
        "valuesPerElement": 3
      },
      "uv0": {
        "valueType": "Float32",
        "valuesPerElement": 2
      },
      "color": {
        "valueType": "UInt8",
        "valuesPerElement": 4
      }
    },
    "featureAttributeOrder": [
      "id",
      "faceRange"
    ],
    "featureAttributes": {
      "id": {
        "valueType": "UInt64",
        "valuesPerElement": 1
      },
      "faceRange": {
        "valueType": "UInt32",
        "valuesPerElement": 2
      }
    }
  }
} 
```


