== vestedGeometryParams

This object extends geometryParams and is the abstract parent object for
all concrete (`vested') geometryParams objects that directly contain a
geometry definition, either as an arrayBufferView or as an embedded
geometry.

=== Related:

link:geometryParams.cmn.adoc[cmn::geometryParams]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|type |string |The primitive type of the geometry defined through a
vestedGeometryParams object. One of: {_triangles_, lines, points}.

|topology |string |Declares the typology of embedded geometry attributes
or those in a geometry resources. When `Indexed`, the indices (faces)
must also be declared. Possible values are: 

- `PerAttributeArray` +
- `InterleavedArray` +
- `Indexed`

|vertexAttributes |link:vertexAttribute.cmn.adoc[vertexAttribute] |A list
of Vertex Attributes, such as Position, Normals, UV coordinates, and
their definitions. While there are standard keywords such as position,
uv0..uv9, normal and color, this is an open, extendable list.

|faces |link:geometryAttribute.cmn.adoc[geometryAttribute] |A list of Face
Attributes, such as indices to build faces, and their definitions. While
there are standard keywords such as position, uv0..uv9, normal and
color, this is an open, extendable list.
|===

=== Examples

==== Example: vestedGeometryParams

[source,json]
----
 {
  "type": "triangles",
  "vertexAttributes": {
    "position": {
      "byteOffset": 8,
      "valueType": "Float32",
      "valuesPerElement": 3
    },
    "normal": {
      "byteOffset": 2672,
      "valueType": "Float32",
      "valuesPerElement": 3
    },
    "uv0": {
      "byteOffset": 5336,
      "valueType": "Float32",
      "valuesPerElement": 2
    },
    "color": {
      "byteOffset": 7112,
      "valueType": "UInt8",
      "valuesPerElement": 4
    }
  }
} 
----
