== Terms and definitions

This document uses the terms defined in Sub-clause 5.3 of <<OGC06-121r9>>, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word "`shall`" (not "`must`") is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== administrative change

change that does not alter the conformance abstract tests for any requirements

NOTE: An administrative change includes typographical errors, changes in wording to improve clarity or consistency, and perfunctory changes such as changes in version numbers.

=== critical Change

change that alters requirements in a way that is known to cause reverse compatibility issues

NOTE: There are no critical changes in OGC I3S Version 1.3

=== substantive change

change that alters requirements in a way that is not deemed to have a high risk for causing reverse compatibility issues

NOTE: The addition of Building Scene Layers is the major substantive change to I3S Version 1.3. The BLS addition does not chnage any of the existing requirements or class descriptions.
