[[Clause_Substantive]]
== Description of Substantive Changes

=== Addition of Building Scene Layers

A Building Scene Layer is a 3D representation of a building model.  A building model may be derived from 3D construction content, such as BIM data, or from a relational database model that contains 3D spatial information.  The I3S BSL capability is designed to model the organization of construction data and groups content into standard engineering disciplines.  Content in a BSL may represent a partial building, an individual building, or multiple buildings on a campus. 

BIM encapsulates best-practice processes in the Architectural Engineering and Construction (AEC) industry to capture virtual (typically in 3D) representations of real-world assets that are commonly used for construction, documentation, and evaluation. BIM processes are applied in multiple domains including architecture and buildings, energy and utilities, or transportation and are typically captured across the lifecycle of an asset.

A BSL layer captures and optimizes BIM data and is typically sourced from formats/standards such as Autodesk Revit, Industry Foundation Classes (IFCs) or Geodatabase Feature data. The I3S BSL enables a user to efficiently share building 3D data for usage on the web, mobile devices as well as desktop platforms. The I3S BSL capability supports visualization and interactive analysis such as view shade analysis or efficient exploration of the many layers of content associated with a BIM model.

An I3S Building Scene Layer also encapsulates the semantic structure of the information in the building model while capturing geometry and attributes that can be used in an application. The BSL captures standard AEC disciplines such as Mechanical, Architectural, Piping, Electrical, and Structural.  Within each discipline, a BSL groups category layers containing 3D objects representing assets of the building such as doors, windows, pipes and walls.  The assets can contain attributes that directly reflect standard and user defined metadata that are stored in the source BIM content or other 3D data source.

NOTE: The  BSL capability to the I3S 1.3 standard is contained in the addition of a number of new classes (normative) including the BSL Scene Layer Profile and informative content to the OGC 1.2 I3S Standard. The BSL extension *did not* result in changes to any of the existing 1.2 classes. 

The following classes are added to the OGC I3S version 1.3 in support of Building Scene Layers:

- BSL_ReadMe.adoc - Entry point and introduction for I3S Building Scene Layers
- layer.bld.adoc - 3DSceneLayer profile for Vuilding Scene Layers
- sublayer.bld.adoc - This class defines the sublayers of a Building Scene Layer.
- subLayerModelName.adoc - Model names allow clients to identify entities of a building without having to rely on a specific name of a category layer, for example. 
- stats.bld.adoc - Define statistics for all building scene layer sublayers.
- attributestats.bld.adoc - Concatenated attribute statistics.
- filter.bld.adoc - Specify rules for display of content in a Building Scene Layer
- filterBlock.bld.adoc - A filter block defines what elements will be filtered with a specific filter mode. 
- filterMode.bld.adoc - Filter mode represents the way elements draw when participating in a filter block.
- filterModeSolid.bld.adoc - Based on rules in filter, display as "solid" if specified.
- filterModeWireFrame.bld.adoc - Based on rules in filter, display as "wireframe" if specified.
- filterAuthoringInfo.bld.adoc - Authoring Info used to generate user interface for authoring clients.
- filterBlockAuthoringInfo.bld.adoc - The filter authoring info object contains metadata about the authoring process for creating a filter block object. 
- filterTypes - The file authoring information for a filter, including the filter type and its value settings.
