== domain (i.e. field)

Attribute domains are rules that describe the legal values of a field
type, providing a method for enforcing data integrity. Attribute domains
are used to constrain the values allowed in a particular attribute.
Using domains helps ensure data integrity by limiting the choice of
values for a particular field. Attribute domains can be shared across
scene layers like 3D Object scene layers or Building Scene Layers.

=== Related:

link:field.cmn.adoc[cmn::field], link:field.cmn.adoc[cmn::field]

=== Properties

[cols=",,",options="header",]
|===
|Property |Type |Description
| *type* | string | Type of domain

Possible values are:

- `codedValue`

- `range`

| *name* | string | Name of the domain. Must be unique per Scene
Layer. | description | string | Description of the domain |
fieldType | string | The field type is the type of attribute field with
which the domain can be associated. Possible values are:

- `FieldTypeDate`

- `FieldTypeSingle`

- `FieldTypeDouble`

- `FieldTypeInteger`

- `FieldTypeSmallInteger`

- `FieldTypeString`

| range | number[2] | Range of the domain. Only numeric types are
possible. 
| codedValues |
link:domainCodedValue.cmn.adoc[domainCodedValue][] | Range of the domain.
Only string types are possible. 
| mergePolicy | string | Merge policy
for the domain. Not used by Scene Layers. Possible values are:

- `MPTDefaultValue`

- `MPTSumValues`

- `MPTAreaWeighted`

| splitPolicy | string | Split policy for the domain. Not used by
Scene Layers. Possible values are:

- `SPTGeometryRatio`

- `SPTDuplicate`

- `SPTDefaultValue`

|===

_Note: properties in *bold* are required_

=== Examples

==== Example: domain

[source,json]
----
 {
  "type": "codedValue",
  "name": "Phases",
  "description": "Phases",
  "codedValues": [
    {
      "name": "Existing",
      "code": 0
    },
    {
      "name": "Baby Room Overhaul",
      "code": 1
    },
    {
      "name": "Roof Garden",
      "code": 2
    }
  ],
  "mergePolicy": "MPTDefaultValue",
  "splitPolicy": "SPTDefaultValue"
} 
----
