== drawingInfo [point cloud profile]

The drawingInfo object contains drawing information for a point cloud scene layer. This is a restricted instance of the common link:drawingInfo.cmn.adoc[cmn:drawingInfo] object.

=== Related:

link:layer.pcsl.adoc[pcsl::layer]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*renderer* | |An object defining the symbology for the layer. There are many possible types and rules for rendering point clouds. Examples are defineing the color of each point in a Point Cloud based on the value of a color attribute or defineing the color of each point in a Point Cloud based on the value of a numeric attribute. The latter approach allows the client to easily map continuous color ramps to minimum and maximum data values of one of the layer's numeric attribute fields.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: drawingInfo

In the following example, the _pointCloudSplatAlgorithm_ renders points
using sizes depending on point density. The _pointCloudStretchRenderer_
defines the color of each point in the data such as a point cloud Layer
based on the value of a numeric attribute. They allow the user to easily
map continuous color ramps to minimum and maximum data values of one of
the layer’s numeric attribute fields.

[source,json]
----
 {
  "renderer": {
    "pointSizeAlgorithm": {
      "type": "pointCloudSplatAlgorithm",
      "scaleFactor": 1.0
    },
    "pointsPerInch": 15.0,
    "field": "ELEVATION",
    "fieldTransformType": "none",
    "type": "pointCloudStretchRenderer",
    "stops": [
      {
        "value": 1.496083,
        "color": [
          88,
          19,
          252,
          255
        ]
      },
      {
        "value": 51.650686,
        "color": [
          8,
          252,
          253,
          255
        ]
      },
      {
        "value": 101.805289,
        "color": [
          242,
          254,
          42,
          255
        ]
      },
      {
        "value": 151.959892,
        "color": [
          255,
          43,
          24,
          255
        ]
      }
    ]
  }
} 
----
