== drawingInfo [common profiles]

DrawingInfo and the associated classes contain the default symbology (drawing information) of an Indexed 3D Scene Layer. When the DrawingInfo object is present in the 3dSceneLayerInfo Class, a client application may symbolize an I3S layer by utilizing the *Renderer* information. Indexed 3d Scene Layers also supports capturing the DrawingInfo object as part of the binary I3S representation This is to support applications that may not be able to dynamically symbolize/override a given I3S layer based on its drawing information. Such a behavior, when present, is indicated by the CachedDrawingInfo Class, indicating the component of the DrawingInfo object that’s captured as part of the binary I3S representation. The Class DrawingInfo has the following structure:

=== Related:

link:3DSceneLayer.cmn.adoc[cmn::3DSceneLayer],
link:3DSceneLayer.psl.adoc[psl::3DSceneLayer]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*renderer* | |An object defining the symbology and other visualization rules for a scene layer.
Examples of renderer types might be one for a shaded relief map or one for rendering point cloud data. This parameter is the name of the renderer rules to use.

|scaleSymbols |boolean |Scale symbols for the layer.
|===

_Note: properties in *bold* are required_
