# geometryUVRegion

UV region for repeated textures. UV regions are required to properly wrap UV coordinates of repeated-texture in texture atlases.  The texture must be written in the atlas with extra border texels to reduce texture sampling artifacts. 

UV regions are defined as a four-component array per vertex : [u_min, v_min, u_max, v_max ], where each component is in the range [0,1] encoded using `normalized UInt16`.

UV could be "wrapped" in the shader such as in the following example:

```
  // UV for this texel is uv in [0, n]
  uv = frac(uv) * (region.zw - region.xy) + region.xy;
```
NOTE: This class is new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:../docs/compressedAttributes.cmn.adoc[compressedAttributes.cmn], link:../docs/geometryBuffer.cmn.adoc[geometryBuffer.cmn]

=== Properties

|===
| Property | Type | Description |
| **type** | string | Color channel values. Must be: `UInt16` |
| **component** | integer | The `default =4`, must be 4. |
| encoding | string | Encoding: Must be: `normalized` |
| binding | string | binding: Possible values are: `per-vertex`: default +
`per-uvregion`: Only valid in conjonction with link:../docs/compressedAttributes.cmn.adoc[compressedAttributes.cmn] when `uvRegionIndex` attribute is present. 
|===

*Note: properties in **bold** are required*

=== Examples 

==== Example: UV region for repeated textures in atlas 

```json
 {
  "type": "UInt16",
  "component": 4
} 
```

