== geometry

This is the common container class for all types of geometry definitions
used in I3S.

=== Related:

link:featureData.cmn.adoc[cmn::featureData],
link:features.cmn.adoc[cmn::features]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*id* |number |Unique ID of the geometry in this store.

|type |string |The type denotes whether the following geometry is
defined by using array buffer views (ArrayBufferView), as an internal
reference (GeometryReference), as a reference to a shared Resource
(SharedResourceReference) or embedded (Embedded).

|transformation |number[16] |3D (4x4) transformation matrix expressed as
a linear array of 16 values.

|params |link:geometryParams.cmn.adoc[geometryParams] |The parameters for
a geometry, as an Embedded GeometryParams object, an ArrayBufferView, a
GeometryReference object, or a SharedResourceReference object.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Geometry

[source,json]
----
 {
  "id": 0,
  "type": "ArrayBufferView",
  "transformation": [
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.0
  ]
} 
----
