== geometryDefinition

The geometry definitions used in OGC I3S version 1.2 and later.

NOTE: This class is new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:3DSceneLayer.cmn.adoc[cmn::3DSceneLayer]

=== Properties

[cols=",,",options="header",]
|===
|Property |Type |Description
| topology | string | Defines the topology type of the mesh.

Must be:

-`triangle`

| *geometryBuffers* | link:geometryBuffer.cmn.adoc[geometryBuffer][1:2]
| Array of geometry representation(s) for this class of meshes. When
multiple representations are listed, Clients should select the most
compact they support (e.g. Draco compressed mesh). For compatibility
reasons, _uncompressed_ geometry buffer is always required and must be
first (i.e. `geometryBuffers[0]`), so array length must be 1 or 2 
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Definition for an OGC Version 1.1 equivalent geometry buffer (`geometryBuffers[0]`) and draco compressed geometry buffer (`geometryBuffers[1]`)

[source,json]
----
 {
  "geometryBuffers": [
    {
      "offset": 8,
      "position": {
        "type": "Float32",
        "component": 3
      },
      "normal": {
        "type": "Float32",
        "component": 3
      },
      "uv0": {
        "type": "Float32",
        "component": 2
      },
      "color": {
        "type": "UInt8",
        "component": 4
      },
      "featureId": {
        "type": "UInt64",
        "component": 1,
        "binding": "per-feature"
      },
      "faceRange": {
        "type": "UInt32",
        "component": 2,
        "binding": "per-feature"
      }
    },
    {
      "compressedAttributes": {
        "encoding": "draco",
        "attributes": [
          "position",
          "uv0",
          "color",
          "feature-index"
        ]
      }
    }
  ]
} 
----
