== lodSelection

The link:../../format/LevelofDetail.md[LoD (Level of Detail)] document
describes in detail the supported LoD model in I3S. The Lod selection
metrics described below provide information for a client application to
determine whether a node’s contents are ``good enough'' to render in the
current 3D view, or if switching to children nodes is more appropriate.
An application could further factor in additional constraints such as
network bandwidth, available memory and target minimum quality goals to
achieve an optimal resource access pattern.

The I3S standard supports multiple LoD selection criteria. Each I3S
profile definition provides additional details on LoD Selection.

=== Related:

link:3DNodeIndexDocument.cmn.md[cmn::3DNodeIndexDocument] ### Properties

[cols=",,",options="header",]
|===
|Property |Type |Description

| *metricType* | string |

Possible values are: +

- `maxScreenThreshold`: A per-node value for the maximum pixel size as
measured in screen pixels. This value indicates the upper limit for the
screen size of the diameter of the node’s minimum bounding sphere (MBS).
In other words, the content referenced by this node will qualify to be
rendered only when the screen size is below the maximum screen threshold
value. Used by the mesh pyramid profile.

- `maxScreenThresholdSQ`: A per-node value for the maximum area of the
projected bounding volume on screen in pixel squared. 3D Viewers may
implement *look-angle dependent* node switching by comparing this metric
with the area of the 2D outline of the oriented-bounding box (OBB) on
screen. ( see
https://pdfs.semanticscholar.org/1f59/8266e387cf367702d16acf5a4e02cc72cb99.pdf[_``Fast
Projected Area Computation for Three-Dimensional Bounding Boxes'',
Dieter Schmalstieg and Robert F. Tobler_] for an efficient algorithm).
If a *look-angle independent* LoD switching is desired, viewers may use
the area of minimum bounding-sphere (MBS) of the node if available or
the MBS of the OBB otherwise. Note: `maxScreenThresholdSQ` may be
related to `maxScreenThreshold` as follow:
-`maxScreenThresholdSQ = PI * 0.25 * maxScreenThreshold * maxScreenThreshold`.Used
by the mesh pyramid profile.

- `screenSpaceRelative`: The scale of the node’s minimum bounding volume.
Used by the point profile.

- `distanceRangeFromDefaultCamera`: The distance from the surface of the
node’s minimum bounding volume to the camera. Used by the point profile.

- `effectiveDensity`: Estimation of the point density covered by the node.
Used by the point cloud profile.

| | *maxError* | number | Maximum metric value, expressed in the CRS of
the vertex coordinates or in reference to other constants such as screen
size. |

|===

_Note: properties in *bold* are required_

=== Examples

==== Example: LoD Selection example

[source,json]
----
 {
  "metricType": "maxScreenThreshold",
  "maxError": 34.87550189480981
} 
----
