== meshMaterial

Mesh material for a node.

NOTE: This class is new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:mesh.cmn.adoc[cmn::mesh]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*definition* |integer |The index in
link:3DSceneLayer.cmn.adoc[layer.materialDefinitions] array.

|resource |integer |Resource id for the material textures. i.e:
`layers/0/nodes/{material.resource}/textures/{tex_name}`. Is *required*
if material declares any textures.

|texelCountHint |integer |Estimated number of texel for the highest
resolution base color texture.
i.e. `texture.mip0.width*texture.mip0.height`. Useful to estimate the
resource cost of this node and/or texel-resolution based LOD switching.
Ignored for un-textured meshes.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Texture material

Texture(s) will be at `layers/0/nodes/6/textures/{tex_name}`. The
`tex_name` is from the 5th material definition. For example, the base
color texture set would be
`layer.materialDefinition[4].pbrMetallicRoughness.baseColorTexture.textureSetDefinitionId`.

[source,json]
----
 {
  "definition": 4,
  "resource": 6,
  "texelCountHint": 1048576
} 
----
