== nodeReference

A nodeReference is a pointer to another node - the parent, a child or a
neighbor. A nodeReference contains a relative URL to the referenced NID,
and a set of meta information which helps determines if a client loads
the data and maintains store consistency.

=== Related:

link:3DNodeIndexDocument.cmn.adoc[cmn::3DNodeIndexDocument] ### Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*id* |string |Tree Key ID of the referenced node represented as string.

|mbs |number[4] |An array of four doubles, corresponding to x, y, z and
radius of the link:mbs.cmn.md[minimum bounding sphere] of a node.

|href |string |The relative URL to the referenced node resource.

|version |string |Version (store update session ID) of the referenced
node.

|featureCount |number |Number of features in the referenced node and its
descendants, down to the leaf nodes.

|obb |link:obb.cmn.adoc[obb] |Describes oriented bounding box.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Node reference for integrated mesh scene layer.

[source,json]
----
 {
  "id": "18",
  "href": "../18",
  "mbs": [
    138.59974403386326,
    -34.929125554424836,
    77.7917739925906,
    245.39599377770242
  ],
  "obb": {
    "center": [
      138.59974403386326,
      -34.929125554424836,
      77.7917739925906
    ],
    "halfSize": [
      186.775208,
      31.6982021,
      158.549973
    ],
    "quaternion": [
      -0.116017461,
      0.276839644,
      0.871147692,
      -0.388588935
    ]
  }
} 
----
