== node [common profiles]

The node object.

NOTE: This class was new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:3DSceneLayer.cmn.adoc[cmn::3DSceneLayer],
link:nodePage.cmn.adoc[cmn::nodePage] 

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*index* |integer |The index in the node array. May be *different than*
material, geometry and attribute `resource` id. See
link:mesh.cmn.adoc[`mesh`] for more information.

|parentIndex |integer |The index of the parent node in the node array.

|lodThreshold |number |When to switch LoD. See
link:nodePageDefinition.cmn.adoc[`nodepages[i].lodSelectionMetricType`]
for more information.

|*obb* |link:obb.cmn.adoc[obb] |Oriented bounding box for this node.

|children |integer[] |index of the children nodes indices.

|mesh |link:mesh.cmn.adoc[mesh] |The mesh for this node. *WARNING:* only
*SINGLE* mesh is supported in OGC version 1.2 (i.e. `length` *must* be 0 or
1).
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Leaf node

[source,json]
----
 {
  "index": 16,
  "parentIndex": 11,
  "lodThreshold": 22968.8125,
  "obb": {
    "center": [
      0.0246379131849151,
      0.0055829490839741725,
      6.388948981650174
    ],
    "halfSize": [
      3.54935479,
      3.52569342,
      2.38895011
    ],
    "quaternion": [
      -0.500083148,
      0.499868125,
      -0.499916822,
      0.500131845
    ]
  },
  "mesh": {
    "material": {
      "definition": 0,
      "resource": 7,
      "texelCountHint": 262144
    },
    "geometry": {
      "definition": 1,
      "resource": 7,
      "vertexCount": 48,
      "featureCount": 1
    },
    "attribute": {
      "resource": 7
    }
  }
} 
----

==== Example: Textured node with two children nodes

[source,json]
----
 {
  "index": 9,
  "parentIndex": 7,
  "lodThreshold": 968831.9375,
  "obb": {
    "center": [
      0.02480438053003459,
      0.00533958737698042,
      14.604276076890528
    ],
    "halfSize": [
      48.7387047,
      11.6107492,
      24.8489189
    ],
    "quaternion": [
      -0.232766122,
      -0.20745486,
      0.675836384,
      -0.667852938
    ]
  },
  "mesh": {
    "material": {
      "definition": 0,
      "resource": 2,
      "texelCountHint": 524288
    },
    "geometry": {
      "definition": 0,
      "resource": 2,
      "vertexCount": 1032,
      "featureCount": 5
    },
    "attribute": {
      "resource": 2
    }
  },
  "children": [
    12,
    13
  ]
} 
----
