== PBR Metalic Roughness Material Model

This class is feature-compatible with https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#materials[glTF
material] except the emissiveTexture (emissive map texture) parameter is not supported in I3S. The emissive map controls the color and intensity of the light being emitted by the material. 

NOTE: This class was new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:materialDefinitions.cmn.adoc[cmn::materialDefinitions]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|baseColorFactor |number[4] |The material’s base color factor.
default=`[1,1,1,1]`

|baseColorTexture |link:materialTexture.cmn.adoc[materialTexture] |The
base color texture.

|metallicFactor |number |the metalness of the material. default=`1.0`

|roughnessFactor |number |the roughness of the material. default=`1.0`

|metallicRoughnessTexture |link:materialTexture.cmn.adoc[materialTexture]
|the metallic-roughness texture.
|===
