== resource

Resource objects are pointers to different types of resources related to
a node, such as the feature data, the geometry attributes and indices,
textures and shared resources.

NOTE: *Warning* The deprecated properties are highlighted. These deprecated elements will remain in the OGC I3S Community Standard until such time as version 2 of this Community Standard is approved. At that time, these deprecated elements will be removed from the standard. 

=== Related:

link:3DNodeIndexDocument.cmn.adoc[cmn::3DNodeIndexDocument] 

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*href* |string |The relative URL to the referenced resource.

|`layerContent` |string[] |*Deprecated.* The list of layer names that
indicates which layer features in the bundle belongs to. The client can
use this information to selectively download bundles.

|`featureRange` |number[] |*Deprecated.* Only applicable for featureData
resources. Provides inclusive indices of the features list in this node
that indicate which features of the node are located in this bundle.

|`multiTextureBundle` |string |*Deprecated.* Only applicable for
textureData resources. TRUE if the bundle contains multiple textures. If
FALSE or not set, clients can interpret the entire bundle as a single
image.

|`vertexElements` |number[] |*Deprecated.* Only applicable for
geometryData resources. Represents the count of elements in
vertexAttributes; multiply by the sum of bytes required for each element
as defined in the defaultGeometrySchema.

|`faceElements` |number[] |*Deprecated.* Only applicable for geometryData
resources. Represents the count of elements in faceAttributes; multiply
by the sum of bytes required for each element as defined in the
defaultGeometrySchema.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: Resource example

[source,json]
----
 {
  "href": "./features/0"
} 
----
