== sharedResources

*Shared Resources are deprecated in OGC version 1.2. They must be included for
backwards compatibility, but are not used.*

Shared resources are models or textures that can be shared among
features within the same layer. They are stored as a JSON file. Each
node has a shared resource that is used by other features in the node or
by features in the subtree of the current node. This approach ensures an
optimal distribution of shared resources across nodes, while maintaining
the node-based updating process. The SharedResource class collects
Material definitions, Texture definitions, Shader definitions and
geometry symbols that need to be instanced.

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*materialDefinitions*
|link:materialDefinition.cmn.adoc[materialDefinition] |Materials describe
how a Feature or a set of Features is to be rendered.

|textureDefinitions |link:textureDefinition.cmn.adoc[textureDefinition] |A
Texture is a set of images, with some parameters specific to the
texture/uv mapping to geometries.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: shared resource

[source,json]
----
 {
  "materialDefinitions": {
    "Mat48": {
      "type": "standard",
      "name": "standard",
      "params": {
        "vertexRegions": false,
        "vertexColors": true,
        "reflectivity": 0,
        "useVertexColorAlpha": false,
        "ambient": [
          0,
          0,
          0
        ],
        "diffuse": [
          1,
          1,
          1
        ],
        "specular": [
          0.09803921568627451,
          0.09803921568627451,
          0.09803921568627451
        ],
        "shininess": 1,
        "renderMode": "solid",
        "cullFace": "none"
      }
    }
  },
  "textureDefinitions": {
    "48": {
      "encoding": [
        "image/jpeg",
        "image/vnd-ms.dds"
      ],
      "wrap": [
        "none",
        "none"
      ],
      "atlas": false,
      "uvSet": "uv0",
      "channels": "rgb",
      "images": [
        {
          "id": "525",
          "size": 64,
          "pixelInWorldUnits": 0,
          "href": [
            "../textures/0_0",
            "../textures/0_0_1"
          ],
          "byteOffset": [
            0,
            0
          ],
          "length": [
            737,
            400
          ]
        }
      ]
    }
  }
} 
----
