== store [point cloud profile]

Describes storage for the layer.

=== Related:

link:layer.pcsl.adoc[pcsl::layer]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|id |string |Id for the store. Not currently used by the point cloud
scene layer.

|*profile* |string |Defines the profile type of the scene layer as point
cloud scene layer. Must be: `PointCloud`

|*version* |string |Point cloud scene layer store version.

|*extent* |number[4] |2D extent of the point cloud scene layer in the
layers spatial reference units.

|*index* |link:index.pcsl.adoc[index] |Describes the index (i.e. bounding
volume tree) of the layer.

|*defaultGeometrySchema*
|link:defaultGeometrySchema.pcsl.adoc[defaultGeometrySchema] |Attribute
description as field.

|geometryEncoding |string |MIME type for the encoding used for the
Geometry Resources. For example: application/octet-stream; version=1.6.

|attributeEncoding |string |MIME type for the encoding used for the
Attribute Resources. For example: application/octet-stream; version=1.6.
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: store

[source,json]
----
 {
  "id": "",
  "profile": "PointCloud",
  "version": "2.0",
  "extent": [
    -105.023403,
    39.740089,
    -105.011746,
    39.757051
  ],
  "index": {
    "nodeVersion": 1,
    "boundingVolumeType": "obb",
    "nodesPerPage": 64,
    "lodSelectionMetricType": "density-threshold"
  },
  "defaultGeometrySchema": {
    "geometryType": "points",
    "header": [],
    "topology": "PerAttributeArray",
    "encoding": "lepcc-xyz",
    "vertexAttributes": {
      "position": {
        "valueType": "Float64",
        "valuesPerElement": 3
      }
    },
    "ordering": [
      "position"
    ]
  }
} 
----
