== textureDefinitionInfo

A texture is a set of images, with some parameters specific to the
texture/uv mapping to geometries.

This Class was part of link:sharedResource.cmn.adoc[sharedResource] that is deprecated
in OGC version 1.2.

NOTE: This class is new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:textureDefinition.cmn.adoc[cmn::textureDefinition]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*encoding* |string[] |MIMEtype - The encoding/content type that is used
by all images in this map

|wrap |string[] |UV wrapping modes, from \{none, repeat, mirror}.

|atlas |boolean |TRUE if the Map represents a texture atlas.

|uvSet |string |The name of the UV set to be used as texture
coordinates.

| channels | string | Indicates channels description. Possible values are: +

- `rgb` +
- `rgba`

| images | link:image.cmn.adoc[image][] | An image is a binary resource,
containing a single raster that can be used to texture a feature or
symbol. 
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: textureDefinition

[source,json]
----
 {
  "encoding": [
    "image/jpeg",
    "image/vnd-ms.dds"
  ],
  "wrap": [
    "none",
    "none"
  ],
  "atlas": false,
  "uvSet": "uv0",
  "channels": "rgb",
  "images": [
    {
      "id": "1161930902884843552",
      "size": 512,
      "pixelInWorldUnits": 0,
      "href": [
        "../textures/0_0",
        "../textures/0_0_1"
      ],
      "byteOffset": [
        0,
        0
      ],
      "length": [
        7461,
        174904
      ]
    }
  ]
} 
----
