== textureSetDefinitionFormat

Describes the formats available for a texture set. Note: JPEG or PNG
must always be provided.

NOTE: This class was new in Version 1.2. However, this class is optional. Implementations of previous versions (1.0 and 1.1) will still work.

=== Related:

link:textureSetDefinition.cmn.adoc[cmn::textureSetDefinition]

=== Properties

[width="100%",cols="34%,33%,33%",options="header",]
|===
|Property |Type |Description
|*name* |string |The location ID for the resource (last segment of the URL path). Must be `"0"` for jpg/png and `"0_0_1"` for DDS and and `"0_0_2"` for KTX.

|*format* |string |The texture format. Possible values are: +

-`jpg`: JPEG compression. No mipmaps. Please note that alpha channel may have been
added after the JPEG stream. This alpha channel is alwasy 8bit and zlib
compressed. Last 4 bytes of the entire stream are the 32 bit offset to
the beginning of the alpha stream (little-endian). +
- `png`: PNG format, no mipmaps +
- `dds`: The DDS header will specify the type of compression and number of mipmaps. *WARNING:* Only DXT1 (no alpha) and DXT5 (alpha channel) are supported. +
- `ktx-etc2`: Khronos group container for ETC2 compressed texture. Mipmap may be available. +
- `ktx2`: Khronos group container for Basis Universal Supercompressed GPU Texture. +

Note: Note: KTX (Khronos Texture) is an efficient, lightweight container format for reliably distributing GPU textures to diverse platforms and applications. https://www.khronos.org/registry/KTX/specs/2.0/ktxspec_v2.html[KTX2] is the container format that supports Basis Universal SuperCompressed GPU texture. |
|===

_Note: properties in *bold* are required_

=== Examples

==== Example: JPEG texture at `/layers/0/nodes/{resource_id}/textures/0`

[source,json]
----
 {
  "name": "0",
  "format": "jpg"
}
----

==== Example: PNG texture at `/layers/0/nodes/{resource_id}/textures/0`

[source,json]
----
 {
  "name": "0",
  "format": "png"
}
----

==== Example: DDS texture at `/layers/0/nodes/{resource_id}/textures/0_0_1`

[source,json]
----
 {
  "name": "0_0_1",
  "format": "dds"
}
----

==== Example: KTX texture at `/layers/0/nodes/{resource_id}/textures/0_0_2`

[source,json]
----
 {
  "name": "0_0_2",
  "format": "ktx-etc2"
}
----

==== Example: ktx2 texture at `/layers/0/nodes/{resource_id}/textures/1`

[source,json]
----
 {
  "name": "1",
  "format": "ktx2"
}
----
